---
# tasks file for restic-backup
- name: download restic
  get_url:
    url: https://github.com/restic/restic/releases/download/v{{ restic_version }}/restic_{{ restic_version }}_linux_amd64.bz2
    dest: /tmp/restic_{{ restic_version }}_linux_amd64.bz2
    checksum: "{{ restic_download_checksum }}"
  register: restic_downloader

# unarchive wont work, waiting for https://github.com/ansible/ansible/pull/23048
- name: unpack restic
  command: bzip2 -d --stdout /tmp/restic_{{ restic_version }}_linux_amd64.bz2 > /usr/local/bin/restic
  when: restic_downloader|changed

- name: get restic-tools
  git:
    repo: 'https://github.com/binarybucks/restic-tools.git'
    dest: /opt/restic-tools

- name: create confdir
  file:
    path: /etc/backup
    state: directory
    owner: root
    group: root
    mode: 'u=rwx,g=rwx'

- name: create local.config
  template:
    src: etc/backup/local.config.j2
    dest: /etc/backup/local.config
    owner: root
    group: root
    mode: 'u=r'

- name: create backup-configs
  template:
    src: etc/backup/repo.j2
    dest: /etc/backup/{{ item.name }}.repo
    owner: root
    group: root
    mode: 'u=r'
  with_items: "{{ backup_destinations }}"
